spring:
  application:
    name: batch-system
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true    # H2 ? ?? ??(????)
        path: /h2-console
  batch:
    job:
      enabled: true
      name: terminatorJob
  main:
    allow-bean-definition-overriding: true #권장 X
logging:
  level:
    root: info
    com:
      system:
        batch: info
